### ISSUE TITLE
Recommended Workflow

### ISSUE THREAD

**Issue by akash-kaul** [TigerGraph-DevLabs/tgSolutionPack#14]
I am just curious about the recommended workflow for using this project. After unzipping the tar file, I noticed the data is not present. Thus, running the command `./runDPInstall.sh` always fails since it cannot find the data files. Is it recommended to download the data separately and then manually add it to the corresponding directory? Any advice or recommendations are very appreciated. Thanks

**Comment by rhardaway** [comment]
Hi Akash,

We are in the process of seperating the scripting from the data, and I agree the instructions are not clear. The plan is to publish the data archive to S3, since the file will become very large. Once you retrieve and extract the data file into the same folder as the scripts, all of the loads will complete.

I've updated the README to reflect this workflow. bob
